name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Gradle (strip -SNAPSHOT)
        id: extract_version
        run: |
          version_line=$(grep "^systemProp.libVersion" gradle.properties)
          raw_version=$(echo "$version_line" | sed -E 's/systemProp\.libVersion[[:space:]]*=[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?)/\1/')
          clean_version=$(echo $raw_version | sed 's/-SNAPSHOT//')
          echo "Raw version: $raw_version"
          echo "Clean version: $clean_version"
          echo "version=$clean_version" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: v${{ steps.extract_version.outputs.version }}
          tag_exists_error: false
          message: "Latest release of the DSP Lib"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
