name: Release Pipeline

on:
  push:
    branches:
      - add-release-pipeline

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Gradle (strip -SNAPSHOT)
        id: extract_version
        run: |
          version_line=$(grep "^version" build.gradle || grep "^version" build.gradle.kts)
          raw_version=$(echo $version_line | sed -E 's/.*["'\'']([0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?)["'\''].*/\1/')
          clean_version=$(echo $raw_version | sed 's/-SNAPSHOT//')
          echo "Raw version: $raw_version"
          echo "Clean version: $clean_version"
          echo "version=$clean_version" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: v${{ steps.extract_version.outputs.version }}
          tag_exists_error: false
          message: "Latest releaseof the DSP Lib"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
